### ISSUE TITLE
I'm having some issues with the code

### ISSUE THREAD

**Issue by phun-ky** [mixable/ColorUtils#1]
I'm trying to write my own stuff for colors in JavaScript, and caught interest in your code. I came across the test here: https://github.com/mixable/color-utils/blob/241f2e7dc8a264da4d70cae2f6ee720778331a50/tests/Color/ConvertTest.php#L25

The expected result should be `[255,255,255]` , since 3 digit hex code `#fff` is the same as `#ffffff`.

**Comment by mixable** [comment]
You are correct. I fixed this issue and updated the code. Thank you!!
